### ISSUE TITLE
Should PL fit use xmax=None 

### ISSUE THREAD

**Issue by charlesmartin14** [CalculatedContent/WeightWatcher#199]
Im going to review this today and confirm or refute that xmax=None gives the same results as xmax=np.max(evals)

If anyone else has results please post them here

**Comment by cdhinrichs** [comment]
There is a test, `test_fit_entropy_on_layer`, that fails with this setting:
```python
	def test_fit_entropy_on_layer(self):
		details = self.watcher.analyze(model=self.model, layers=[28])
		expected = details.fit_entropy.to_numpy()[0]
		
		import powerlaw
		esd = self.watcher.get_ESD(layer=28)
		fit1 = powerlaw.Fit(esd,  xmax=np.max(esd))
		fit2 = powerlaw.Fit(esd,  xmax=None)
		fit3 = WW_powerlaw.Fit(esd)

		print(fit1.alpha, fit1.sigma, fit1.xmin, RMT_Util.line_entropy(fit1.Ds))
		print(fit2.alpha, fit2.sigma, fit2.xmin, RMT_Util.line_entropy(fit2.Ds))
		print(fit3.alpha, fit3.sigma, fit3.xmin, RMT_Util.line_entropy(fit3.Ds))

		actual = RMT_Util.line_entropy(fit2.Ds)
		self.assertAlmostEqual(expected, actual, None, '', 0.01)
```

I've instrumented it so that it compares the existing method, i.e. `xmax = np.max(esd)` with setting `xmax=None`, and also against my numpy-only reimplementation. This test prints out:
```
xmax = np.max(esd) 2.167513468986555 0.03413256835412088 0.34178920920977085 2.8923260965013284
xmax = None             2.161949351116024 0.0336690852298874   0.33522863950906795 2.8162618643641024
numpy powerlaw      2.161949351116024 0.0336690852298874   0.33522863950906795 2.8162618643641024
F
======================================================================
FAIL: test_fit_entropy_on_layer (tests.test.Test_VGG11)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/darda/WeightWatcher/tests/test.py", line 1259, in test_fit_entropy_on_layer
    self.assertAlmostEqual(expected, actual, None, '', 0.01)
AssertionError: 2.8143635507565032 != 2.8923260965013284 within 0.01 delta (0.0779625457448252 difference) : 
```

As you can see, the numpy reimplementation agrees perfectly with the `xmax=None` option, but there is a slight discrepancy with the previous method.

I recommend the test be changed to use the `xmax=None` option in powerlaw, so that it's still checking against the numpy version.

**Comment by cdhinrichs** [comment]
The test `test_compute_alphas` fails with this setting, though I also note that it has been broken since the change to FAST_SVD.
As of right now,

- With `ACCURATE_SVD` and `xmax=np.max(data)` and `powerlaw.Fit` it passes
- With `ACCURATE_SVD` and `xmax=None` and `powerlaw.Fit` it fails for alpha  `1.748594297885536 != 1.65014`
- With `FAST_SVD` and `xmax=np.max(data)` and `powerlaw.Fit` it fails for spectral norm `20.215107 != 20.2149`
- With `FAST_SVD` and `xmax=None` and `powerlaw.Fit` it fails for alpha `1.7485943701157503 != 1.65014`

- With `ACCURATE_SVD` and `xmax=None` (effectively) and `WWFit` it fails for alpha `1.748594297885536 != 1.65014`
- With `FAST_SVD` and `xmax=None` (effectively) and `WWFit` it fails for alpha `1.748594297885536 != 1.65014`

I recommend we enforce `ACCURATE_SVD` in the call to `analyze`, and change the fist 2 expected alphas to 1.74859 and 1.66595.

**Comment by cdhinrichs** [comment]
The test `test_fix_fingers_xmin_peak` fails with this setting.

As of right now, 

- With `ACCURATE_SVD` and `xmax=np.max(data)` and `powerlaw.Fit` it passes
- With `ACCURATE_SVD` and `xmax=None` and `powerlaw.Fit` it fails with `1.7207925908210036 != 7.116304`
- With `FAST_SVD` and `xmax=np.max(data)` and `powerlaw.Fit` it passes
- With `FAST_SVD` and `xmax=None` and `powerlaw.Fit` it fails with `1.7207916701875228 != 7.116304`
- With `ACCURATE_SVD` and `xmax=None` (effectively) and `WWFit` it fails with `1.7207916701875228 != 7.116304`
- With `FAST_SVD` and `xmax=None` (effectively) and `WWFit` it fails with `1.7207916701875228 != 7.116304`

Since `WW_fit` replicates the behavior of `powerlaw` when `xmax=None`, it makes no difference whether it is used, or `powerlaw` itself. Fast SVD makes not difference either.

**Comment by charlesmartin14** [comment]
These should all be fixed now; you may wnt to independently verify
