### ISSUE TITLE
Bug in the MP fits of the randomized ESDs

### ISSUE THREAD

**Issue by anonymouspapers** [CalculatedContent/WeightWatcher#60]
Please be aware that there remains some bug in the MP fits of the randomized ESDs

In some cases, the MP fit looks quite off, but , in fact, the fit is just wrong

Here is an example from VGG11, layer 8; This is the current code (0.4.7)
<img width="708" alt="Screen Shot 2021-05-30 at 10 34 11 PM" src="https://user-images.githubusercontent.com/60992715/120144741-59751580-c197-11eb-926b-52617008c66f.png">

This is the correct fit
<img width="762" alt="Screen Shot 2021-05-30 at 10 34 03 PM" src="https://user-images.githubusercontent.com/60992715/120144667-3480a280-c197-11eb-89e0-d45d708caa21.png">

**Comment by charlesmartin14** [comment]
Thanks for submitting

I suspect the scale is somehow misset
This appears in a few other places as well.
I will fix in the next minor release

**Comment by charlesmartin14** [comment]
From what I can tell, different frameworks set the normalization of W differently, and I have not figured out a way to automatically detect and fix this yet in  RMT (random matrix theory), we expect W to say a Gaussian random matrix, with variance 1.0, and normalized by 1/N.  But the frameworks don't actually do this--they might use Glorot normalization (which is not 100% the same ) , and they frequently rescale W by say 1/(N+M), or sqrt(2/(N+M)), rather than 1/N.  So when we initialize the DNN layers, we need to figure out what was done, and then move back to this normalization

My best idea right now is to simply let the user enter their own normalization function, i.e:
`watcher.analyze(..., normalizer=(lambda N, M, rf: (N/(N+M))))
`
So that in the code we can, for every layer, we can fix the normalization using:
`W = W*normalized(N,M,rf)
`I think this will work for the Transformers (not sure about the Conv2D layers though)

-----

Here is an footnote from our long paper which discusses this
(its buried in a footnote because it is a minor tweak to the theory--but for for the MP fits to work , its critical to get this right)
![image](https://user-images.githubusercontent.com/498448/128056743-2dbb9a5c-0389-459e-a46d-550dfe4030f6.png)

**Comment by nsfzyzz** [comment]
The following seems to help in my case. 

First, change the range of sigma in the following function.
https://github.com/CalculatedContent/WeightWatcher/blob/618a3d3f707409ce044f7ad5809359128a796a4e/weightwatcher/RMT_Util.py#L518
Add the following two lines.
`sigma_scaling_factor = calc_sigma(Q, evals)`
`sigma_range = (slice(0.05 * sigma_scaling_factor, 2.0 * sigma_scaling_factor, 0.01 * sigma_scaling_factor),)`

Second, change the following condition.
https://github.com/CalculatedContent/WeightWatcher/blob/618a3d3f707409ce044f7ad5809359128a796a4e/weightwatcher/RMT_Util.py#L462
Change this condition to the following.
`if (b < xde[np.where(yde == max(yde))][0] ) | (b > max(xde)) | (a > xde[np.where(yde == max(yde))][0]):`

Third, change the following normalization code.
https://github.com/CalculatedContent/WeightWatcher/blob/618a3d3f707409ce044f7ad5809359128a796a4e/weightwatcher/weightwatcher.py#L2028
I am not sure why the original code uses N. But I used the following so that the eigenvalues are normalized to have an average value of 1.
`Wscale = np.sqrt(to_plot.shape[0]*rf)/Wnorm`

I test locally on a bunch of NLP models with only linear layers. The results seem to be fine.

![image](https://user-images.githubusercontent.com/13740654/128584671-2cc4ad2c-4d36-4927-8646-40271dc5947e.png)


There are still some cases that I do not know how to solve. For example, for CV models, it is possible that the eigenvalues do not follow the quarter circle function. In some other cases, the ESD is not very similar to any MP distribution or QC distribution, such as the following figure.

![image](https://user-images.githubusercontent.com/13740654/128584606-899cd576-8661-4d49-baae-f0ef4275f5f4.png)

**Comment by charlesmartin14** [comment]
I have implemented your fix, but the VGG model does not look correct
Can you please confirm that the fix works on all plots in the VGG notebooks provided
WeightWatcher-VGG.ipynb
WeightWatcher-VGG-Random.ipynb
and the GPT notebooks
The fix appears to break the QC plots, when N=M, Q=1

I am assuming , as a hack, we can use different codes for Q=1 and Q>1
And then test the approach on a wide range of models , CV and NLP (

**Comment by charlesmartin14** [comment]
>  For example, for CV models, it is possible that the eigenvalues do not follow the quarter circle function. 
If the matrix is randomized, it will mostly follow the QC law
I suspect this is a scaling issue

**Comment by nsfzyzz** [comment]
Ok, so I think the previous fix still has a problem. On my side, I tried to change 
https://github.com/CalculatedContent/WeightWatcher/blob/618a3d3f707409ce044f7ad5809359128a796a4e/weightwatcher/weightwatcher.py#L2028
to `Wscale = np.sqrt(to_plot.shape[0])/Wnorm`.

Previously, I suggested `Wscale = np.sqrt(to_plot.shape[0]*rf)/Wnorm`. I did not understand the meaning of rf and assumed that is always 1.

Now, the VGG seems to give a proper result.

![image](https://user-images.githubusercontent.com/13740654/128615721-0e75f392-da7b-46e8-bab6-4fda9e421d10.png)

Could you see if that works?

**Comment by nsfzyzz** [comment]
Another potential issue is that Q can be < 1.0 in the following line.
https://github.com/CalculatedContent/WeightWatcher/blob/618a3d3f707409ce044f7ad5809359128a796a4e/weightwatcher/weightwatcher.py#L2022

I think one should add an if-condition to check if N and M should be flipped.

**Comment by charlesmartin14** [comment]
I think this is now fixed, see #60
closing
